"""
Django settings for hlh_project project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path

# ================================
# PATHS
# ================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ================================
# SECURITY & DEBUG
# ================================
SECRET_KEY = 'django-insecure-7!7avv+8=!24cij#n3^@to3criu$@xpr4+4pas467oz)!tzq)f'
DEBUG = True
ALLOWED_HOSTS = []


# ================================
# APPLICATIONS
# ================================
INSTALLED_APPS = [
    # My apps
    'home_logs',
    'accounts',

    # Default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Security / third-party
    'axes',  # 🚀 For brute-force protection
]


# ================================
# MIDDLEWARE
# ================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 🚀 Axes security middleware
    'axes.middleware.AxesMiddleware',
]


# ================================
# AUTHENTICATION BACKENDS
# ================================
AUTHENTICATION_BACKENDS = [
    # 🚀 Axes authentication backend (updated for django-axes 5.0+)
    'axes.backends.AxesStandaloneBackend',
    
    # Django's default authentication backend
    'django.contrib.auth.backends.ModelBackend',
]


# ================================
# URLS / WSGI
# ================================
ROOT_URLCONF = 'hlh_project.urls'
WSGI_APPLICATION = 'hlh_project.wsgi.application'


# ================================
# TEMPLATES
# ================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 🚀 Global templates folder (for base.html etc.)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ================================
# DATABASE
# ================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ================================
# PASSWORDS
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🚀 Custom user model
AUTH_USER_MODEL = 'accounts.User'


# ================================
# INTERNATIONALIZATION
# ================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ================================
# STATIC FILES
# ================================
STATIC_URL = 'static/'


# ================================
# DEFAULT PRIMARY KEY
# ================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ================================
# EMAIL / PASSWORD RESET
# ================================
# 🚀 Dev mode: emails will print to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 🚀 Production SMTP setup (replace with real values later)
EMAIL_HOST = 'smtp.yourservice.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your@email.com'
EMAIL_HOST_PASSWORD = 'yourpassword'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

# 🚀 Password reset token expiration (24 hrs)
PASSWORD_RESET_TIMEOUT = 86400


# ================================
# AXES CONFIG (Brute-force defense)
# ================================
AXES_FAILURE_LIMIT = 5       # 5 failed attempts
AXES_COOLOFF_TIME = 1        # lockout for 1 hour
AXES_RESET_ON_SUCCESS = True # reset counter when login succeeds
AXES_NEVER_LOCK_OUT = True

LOGIN_URL = '/accounts/login/'